import {
  AimOutlined,
  ApiOutlined,
  AppstoreAddOutlined,
  AppstoreOutlined,
  AudioOutlined,
  BackwardOutlined,
  BankOutlined,
  BarChartOutlined,
  BarcodeOutlined,
  BarsOutlined,
  BellOutlined,
  BugOutlined,
  BulbOutlined,
  CalendarOutlined,
  CameraOutlined,
  CarryOutOutlined,
  CheckCircleOutlined,
  CheckOutlined,
  CloseCircleOutlined,
  CloseOutlined,
  CloudOutlined,
  CodeOutlined,
  CommentOutlined,
  CompassOutlined,
  ContactsOutlined,
  CreditCardOutlined,
  CustomerServiceOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DeleteOutlined,
  DisconnectOutlined,
  DollarOutlined,
  DownloadOutlined,
  EditOutlined,
  EllipsisOutlined,
  EnvironmentOutlined,
  ExclamationCircleOutlined,
  ExperimentFilled,
  ExperimentOutlined,
  EyeInvisibleOutlined,
  EyeOutlined,
  FastForwardOutlined,
  FileAddOutlined,
  FileDoneOutlined,
  FileExcelOutlined,
  FileImageOutlined,
  FileOutlined,
  FilePdfOutlined,
  FilePptOutlined,
  FileProtectOutlined,
  FileSearchOutlined,
  FileTextOutlined,
  FileUnknownOutlined,
  FileWordOutlined,
  FileZipOutlined,
  FilterOutlined,
  FireOutlined,
  FlagOutlined,
  FolderOpenOutlined,
  FolderOutlined,
  FormOutlined,
  ForwardOutlined,
  FrownOutlined,
  GiftOutlined,
  GlobalOutlined,
  HeartFilled,
  HeartOutlined,
  HistoryOutlined,
  HomeOutlined,
  HourglassOutlined,
  IdcardOutlined,
  InfoCircleOutlined,
  LayoutOutlined,
  LineChartOutlined,
  LinkOutlined,
  LockOutlined,
  MailOutlined,
  MehOutlined,
  MenuOutlined,
  MessageOutlined,
  MinusCircleOutlined,
  OrderedListOutlined,
  PaperClipOutlined,
  PauseCircleOutlined,
  PhoneOutlined,
  PictureOutlined,
  PieChartOutlined,
  PlayCircleOutlined,
  PlusCircleOutlined,
  PlusOutlined,
  PrinterOutlined,
  ProfileOutlined,
  ProjectOutlined,
  PushpinFilled,
  PushpinOutlined,
  QrcodeOutlined,
  QuestionCircleOutlined,
  RedoOutlined,
  ReloadOutlined,
  RocketFilled,
  RocketOutlined,
  SaveOutlined,
  ScanOutlined,
  ScheduleOutlined,
  SearchOutlined,
  SettingFilled,
  SettingOutlined,
  ShopFilled,
  ShopOutlined,
  ShoppingCartOutlined,
  SmileOutlined,
  SolutionOutlined,
  SoundOutlined,
  StarFilled,
  StarOutlined,
  StepBackwardOutlined,
  StepForwardOutlined,
  StopOutlined,
  SyncOutlined,
  TableOutlined,
  TagOutlined,
  TagsOutlined,
  TeamOutlined,
  ThunderboltOutlined,
  ToolOutlined,
  TrophyOutlined,
  UndoOutlined,
  UnlockOutlined,
  UnorderedListOutlined,
  UploadOutlined,
  UserAddOutlined,
  UsergroupAddOutlined,
  UserOutlined,
  VideoCameraOutlined,
  WarningOutlined,
} from '@ant-design/icons';

export const iconMap: { [key: string]: React.ComponentType } = {
  'file-text': FileTextOutlined,
  home: HomeOutlined,
  users: UserOutlined,
  setting: SettingOutlined,
  dashboard: DashboardOutlined,
  piechart: PieChartOutlined,
  barchart: BarChartOutlined,
  linechart: LineChartOutlined,
  table: TableOutlined,
  calendar: CalendarOutlined,
  team: TeamOutlined,
  contacts: ContactsOutlined,
  project: ProjectOutlined,
  database: DatabaseOutlined,
  tag: TagOutlined,
  tags: TagsOutlined,
  folder: FolderOutlined,
  folderopen: FolderOpenOutlined,
  plus: PlusOutlined,
  edit: EditOutlined,
  delete: DeleteOutlined,
  search: SearchOutlined,
  filter: FilterOutlined,
  bell: BellOutlined,
  mail: MailOutlined,
  phone: PhoneOutlined,
  star: StarOutlined,
  heart: HeartOutlined,
  check: CheckOutlined,
  close: CloseOutlined,
  warning: WarningOutlined,
  info: InfoCircleOutlined,
  question: QuestionCircleOutlined,
  lock: LockOutlined,
  unlock: UnlockOutlined,
  upload: UploadOutlined,
  download: DownloadOutlined,
  cloud: CloudOutlined,
  shop: ShopOutlined,
  shoppingcart: ShoppingCartOutlined,
  creditcard: CreditCardOutlined,
  money: DollarOutlined,
  bank: BankOutlined,
  globe: GlobalOutlined,
  settingfilled: SettingFilled,
  useradd: UserAddOutlined,
  usergroupadd: UsergroupAddOutlined,
  solution: SolutionOutlined,
  smile: SmileOutlined,
  frown: FrownOutlined,
  meh: MehOutlined,
  rocket: RocketOutlined,
  experiment: ExperimentOutlined,
  file: FileOutlined,
  fileadd: FileAddOutlined,
  filedone: FileDoneOutlined,
  fileexcel: FileExcelOutlined,
  filepdf: FilePdfOutlined,
  fileimage: FileImageOutlined,
  filezip: FileZipOutlined,
  fileword: FileWordOutlined,
  fileppt: FilePptOutlined,
  fileunknown: FileUnknownOutlined,
  fileprotect: FileProtectOutlined,
  filesearch: FileSearchOutlined,
  history: HistoryOutlined,
  hourglass: HourglassOutlined,
  sync: SyncOutlined,
  reload: ReloadOutlined,
  redo: RedoOutlined,
  undo: UndoOutlined,
  eye: EyeOutlined,
  eyeinvisible: EyeInvisibleOutlined,
  link: LinkOutlined,
  disconnect: DisconnectOutlined,
  pushpin: PushpinOutlined,
  paperclip: PaperClipOutlined,
  calendarcheck: CalendarOutlined,
  calendarclock: CalendarOutlined,
  calendarplus: CalendarOutlined,
  calendarminus: CalendarOutlined,
  calendarx: CalendarOutlined,
  flag: FlagOutlined,
  trophy: TrophyOutlined,
  gift: GiftOutlined,
  fire: FireOutlined,
  thunderbolt: ThunderboltOutlined,
  customer: CustomerServiceOutlined,
  message: MessageOutlined,
  comment: CommentOutlined,
  form: FormOutlined,
  profile: ProfileOutlined,
  contactsbook: ContactsOutlined,
  idcard: IdcardOutlined,
  carryout: CarryOutOutlined,
  schedule: ScheduleOutlined,
  scan: ScanOutlined,
  qr: QrcodeOutlined,
  barcode: BarcodeOutlined,
  compass: CompassOutlined,
  aim: AimOutlined,
  environment: EnvironmentOutlined,
  pushpinfilled: PushpinFilled,
  shopfilled: ShopFilled,
  starfilled: StarFilled,
  heartfilled: HeartFilled,
  checkcircle: CheckCircleOutlined,
  closecircle: CloseCircleOutlined,
  infocircle: InfoCircleOutlined,
  warningcircle: WarningOutlined,
  questioncircle: QuestionCircleOutlined,
  exclamationcircle: ExclamationCircleOutlined,
  pluscircle: PlusCircleOutlined,
  minuscircle: MinusCircleOutlined,
  playcircle: PlayCircleOutlined,
  pausecircle: PauseCircleOutlined,
  stop: StopOutlined,
  forward: ForwardOutlined,
  backward: BackwardOutlined,
  fastforward: FastForwardOutlined,
  stepforward: StepForwardOutlined,
  stepbackward: StepBackwardOutlined,
  sound: SoundOutlined,
  audio: AudioOutlined,
  video: VideoCameraOutlined,
  camera: CameraOutlined,
  picture: PictureOutlined,
  save: SaveOutlined,
  printer: PrinterOutlined,
  tool: ToolOutlined,
  wrench: ToolOutlined,
  bulb: BulbOutlined,
  experimentfilled: ExperimentFilled,
  rocketfilled: RocketFilled,
  bug: BugOutlined,
  api: ApiOutlined,
  code: CodeOutlined,
  layout: LayoutOutlined,
  appstore: AppstoreOutlined,
  appstoreadd: AppstoreAddOutlined,
  menu: MenuOutlined,
  unorderedlist: UnorderedListOutlined,
  orderedlist: OrderedListOutlined,
  bars: BarsOutlined,
  ellipsis: EllipsisOutlined,
};
